import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <div className="h-15 bg-amber-400 fixed w-full">
            navbar
          </div>
          <div className="flex  ">
            <div className="w-40 h-[100vh] pt-15 calc bg-purple-300">
              sidebar
            </div>
           <div className="p-5 pt-20">
              {children}
           </div>
          </div>
         
        </div>
      </body>
    </html>
  );
}
